sudo: false
language: node_js
node_js:
- '4'
- '6'

services: mongodb

deploy:
  provider: npm
  email: refack
  api_key:
    secure: a/Jy+kf7oOpjhVNrbXufwDufn6BFU1pVgZLUaV68zhnmnwTNLMFs5IwgxZfNgBswcLVfiw3Kdq/owbO9KD6yb+pa71oMr/5s1uyjwi9y6R6I4NZ3S9nGG7YbxPx3RFW3F81USLbxFopYfCbk77s0o3//pEp9gtglcUVRTCIbKD8=
  on:
    all_branches: true
    tags: true
    node: '6'
    repo: node4good/formage
